import type { Metadata } from 'next';

import '../assets/styles/globals.css';
import Notification from '@/components/notification';
import { airbnb } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={airbnb.variable}>
        {children}

        {/* React-Toastify */}
        <Notification />
      </body>
    </html>
  );
}
