import type { Metadata } from 'next';

import '../assets/styles/globals.css';
import Notification from '@/components/notification';
import AuthProvider from '@/components/providers/auth.provider';
import { KEY } from '@/constants/key';
import { getCookie } from '@/lib/cookies';
import { airbnb } from '@/lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const token = getCookie(KEY.TOKEN)?.value;
  const user = getCookie(KEY.USER)?.value;

  return (
    <html lang='en'>
      <body className={airbnb.variable}>
        <AuthProvider
          initialState={{
            token,
            user: user && JSON.parse(user),
          }}
        >
          {children}

          {/* React-Toastify */}
          <Notification />
        </AuthProvider>
      </body>
    </html>
  );
}
